### ISSUE TITLE
Code highlighter doesnt work on website.

### ISSUE THREAD

**Issue by linuxd3v** [mezzio/mezzio-swoole#83] opened 2021-12-20 21:03 UTC
### Bug Report
syntax highlighter doesnt work on website.

#### Summary

Code highlighting on website is illegible, its dark gray on slightly less darker gray - hard to read.

#### Current behavior

Hard to read code examples

#### How to reproduce

Visit this page https://docs.mezzio.dev/mezzio-swoole/v4/logging/  see this code block:
![gray](https://user-images.githubusercontent.com/3410509/146832076-e3acf1a3-254e-484c-83e6-522f1f931af7.png)

#### Expected behavior

we should be seeing nice and fancy syntax highlights in multiple colors that are other then gray

**Comment by froschdesign** [comment] 2021-12-20 21:07
The related workflow produces an error: https://github.com/mezzio/mezzio-swoole/runs/4549933158?check_suite_focus=true#step:3:49

**Comment by froschdesign** [comment] 2022-01-28 10:02
@weierophinney 
The problem is this part:

```bash
print_info "Deploying documentation"
remote_branch="${PUBLISH_BRANCH}"
local_dir="${HOME}/ghpages_${RANDOM}"

if git clone --depth=1 --single-branch --branch "${remote_branch}" "${remote_repo}" "${local_dir}"; then
    print_info "- Cloning branch ${remote_branch} from ${remote_repo} to ${local_dir} and removing previous files"
    cd "${local_dir}"

    git rm -r --ignore-unmatch '*'
else
    print_info "- Creating new ${remote_branch} branch on ${remote_repo} in ${local_dir}"
    git clone --depth=1 --single-branch --branch master "${remote_repo}" "${local_dir}"
    cd "${local_dir}"
    git checkout --orphan "${remote_branch}"
    git rm -rf .
fi
```
https://github.com/laminas/documentation-theme/blob/7526b6db61db2e94d8a21e6468a95aac1fc0148a/github-actions/docs/entrypoint.sh#L81-L96

Maybe the Mezzio repositories don't have rights to clone repositories from Laminas?!

**Comment by weierophinney** [comment] 2022-01-31 14:12
> Maybe the Mezzio repositories don't have rights to clone repositories from Laminas?!

It's using the `git` protocol, no SSH, so permissions should not be an issue.

I'll see if I can troubleshoot it this week.

**Comment by weierophinney** [comment] 2022-01-31 17:42
@froschdesign I stand corrected; it's using git over ssh. So we'd basically only need to change how the build action clones to use `git://` as the schema.

**Comment by weierophinney** [comment] 2022-01-31 17:49
Argghh... reading this, I got confused as to what is happening.

Yes, the issue is exactly where you indicated, @froschdesign - however, it's **after** documentation has been built. This is the logic for then **pushing** the documentation to the gh_pages branch. It tries to check out the gh_pages branch of the repo locally, and that's where it's failing with the permissions issue. It's not trying to checkout a Laminas repo, it's having issues checking out _itself_.

It may be an issue of a missing org or repo secret; I'm continuing to review.

**Comment by weierophinney** [comment] 2022-01-31 19:58
@froschdesign My experiments with laminas/documentation-theme worked; syntax highlighting is fixed on this one!

**Closed as completed by weierophinney** 2022-01-31 19:58 UTC
Labels: Bug, Documentation
